/***************************************************************************
 *   Copyright (C) 2006 by Dominik Seichter                                *
 *   domseichter@web.de                                                    *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU Library General Public License as       *
 *   published by the Free Software Foundation; either version 2 of the    *
 *   License, or (at your option) any later version.                       *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU Library General Public     *
 *   License along with this program; if not, write to the                 *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of portions of this program with the      *
 *   OpenSSL library under certain conditions as described in each         *
 *   individual source file, and distribute linked combinations            *
 *   including the two.                                                    *
 *   You must obey the GNU General Public License in all respects          *
 *   for all of the code used other than OpenSSL.  If you modify           *
 *   file(s) with this exception, you may extend this exception to your    *
 *   version of the file(s), but you are not obligated to do so.  If you   *
 *   do not wish to do so, delete this exception statement from your       *
 *   version.  If you delete this exception statement from all source      *
 *   files in the program, then also delete it here.                       *
 ***************************************************************************/

/*
 * WARNING: This file was automatically generated by Beautiful Capi!
 * Do not edit this file! Please edit the source API description.
 *
 * Beautiful Capi project:
 * https://github.com/PetrPPetrov/beautiful-capi
 *
 * PoDoFo API description project:
 * https://github.com/GkmSoft/podofo-capi
 */


virtual ~PdfFont() {}
virtual bool IsBold() const = 0;
virtual bool IsItalic() const = 0;
virtual void SetStrikeOut(bool bStrikeOut) = 0;
virtual bool IsStrikeOut() const = 0;
virtual PoDoFo::PdfName GetIdentifier() const = 0;
virtual PoDoFo::PdfEncoding* GetEncoding() const = 0;
virtual PoDoFo::PdfFontMetrics* GetFontMetrics() const = 0;
virtual PoDoFo::PdfFontMetrics* GetFontMetrics2() = 0;
virtual void WriteStringToStream(PoDoFo::PdfString rsString, PoDoFo::PdfStream* pStream) = 0;
virtual void EmbedFont() = 0;
virtual void AddUsedSubsettingGlyphs(PoDoFo::PdfString sText, long lStringLen) = 0;
virtual void WriteStringToStream(PoDoFo::PdfString pszGlyphName, PoDoFo::PdfStream* pStream) = 0;
virtual void EmbedSubsetFont() = 0;
virtual bool IsSubsetting() const = 0;
virtual float GetFontSize() const = 0;
virtual void SetFontSize(float font_size) = 0;
virtual float GetFontScale() const = 0;
virtual void SetFontScale(float font_scale) = 0;
virtual float GetFontCharSpace() const = 0;
virtual void SetFontCharSpace(float font_char_space) = 0;
virtual float GetWordSpace() const = 0;
virtual void SetWordSpace(float word_space) = 0;
virtual bool IsUnderlined() const = 0;
virtual void SetUnderlined(bool underlined) = 0;
