/***************************************************************************
 *   Copyright (C) 2006 by Dominik Seichter                                *
 *   domseichter@web.de                                                    *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU Library General Public License as       *
 *   published by the Free Software Foundation; either version 2 of the    *
 *   License, or (at your option) any later version.                       *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU Library General Public     *
 *   License along with this program; if not, write to the                 *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of portions of this program with the      *
 *   OpenSSL library under certain conditions as described in each         *
 *   individual source file, and distribute linked combinations            *
 *   including the two.                                                    *
 *   You must obey the GNU General Public License in all respects          *
 *   for all of the code used other than OpenSSL.  If you modify           *
 *   file(s) with this exception, you may extend this exception to your    *
 *   version of the file(s), but you are not obligated to do so.  If you   *
 *   do not wish to do so, delete this exception statement from your       *
 *   version.  If you delete this exception statement from all source      *
 *   files in the program, then also delete it here.                       *
 ***************************************************************************/

/*
 * WARNING: This file was automatically generated by Beautiful Capi!
 * Do not edit this file! Please edit the source API description.
 *
 * Beautiful Capi project:
 * https://github.com/PetrPPetrov/beautiful-capi
 *
 * PoDoFo API description project:
 * https://github.com/GkmSoft/podofo-capi
 */


virtual ~PdfMemDocumentImpl() {}
virtual void Load(const char* pszFilename, bool bForUpdate) = 0;
virtual void Load(const char* pBuffer, long lLen, bool bForUpdate) = 0;
virtual void Load(PoDoFo::PdfRefCountedInputDevice rDevice, bool bForUpdate) = 0;
virtual bool IsLoaded() const = 0;
virtual void Write(const char* pszFilename) = 0;
virtual void Write(PoDoFo::PdfOutputDeviceImpl* pDevice) = 0;
virtual void WriteUpdate(const char* pszFilename) = 0;
virtual void WriteUpdate(PoDoFo::PdfOutputDeviceImpl* rDevice, bool bTruncate) = 0;
virtual void AddPdfExtension(const char* ns, PoDoFo::pdf_int64 level) = 0;
virtual bool HasPdfExtension(const char* ns, PoDoFo::pdf_int64 level) const = 0;
virtual void RemovePdfExtension(const char* ns, PoDoFo::pdf_int64 level) = 0;
virtual Bcapi::Vector<PoDoFo::PdfExtension> GetPdfExtensions() const = 0;
virtual void SetPassword(const char* sPassword) = 0;
virtual void SetEncrypted(const char* userPassword, const char* ownerPassword, int protection, PoDoFo::PdfEncryptImpl::EPdfEncryptAlgorithm eAlgorithm, PoDoFo::PdfEncryptImpl::EPdfKeyLength eKeyLength) = 0;
virtual void SetEncrypted(PoDoFo::PdfEncryptImpl eKeyLength) = 0;
virtual bool GetEncrypted() const = 0;
virtual bool IsLinearized() const = 0;
virtual PoDoFo::PdfVecObjects GetObjects() const = 0;
virtual PoDoFo::PdfVecObjects GetObjects() = 0;
virtual PoDoFo::PdfObjectImpl GetCatalog() = 0;
virtual PoDoFo::PdfObjectImpl* GetCatalog() = 0;
virtual PoDoFo::PdfObjectImpl* GetTrailer() const = 0;
virtual PoDoFo::PdfObjectImpl* GetStructTreeRoot() const = 0;
virtual PoDoFo::PdfObjectImpl* GetMetadata() const = 0;
virtual PoDoFo::PdfObjectImpl* GetMarkInfo() const = 0;
virtual PoDoFo::PdfObjectImpl* GetLanguage() const = 0;
virtual PoDoFo::PdfObjectImpl* GetFont(PoDoFo::PdfObjectImpl* pObject) = 0;
virtual PoDoFo::PdfMemDocumentImpl* InsertPages(PoDoFo::PdfMemDocumentImpl rDoc, int inFirstPage, int inNumPages) = 0;
virtual void DeletePages(int inFirstPage, int inNumPages) = 0;
virtual bool IsPrintAllowed() const = 0;
virtual bool IsEditAllowed() const = 0;
virtual bool IsCopyAllowed() const = 0;
virtual bool IsEditNotesAllowed() const = 0;
virtual bool IsFillAndSignAllowed() const = 0;
virtual bool IsAccessibilityAllowed() const = 0;
virtual bool IsDocAssemblyAllowed() const = 0;
virtual bool IsHighPrintAllowed() const = 0;
virtual void FreeObjectMemory(PoDoFo::PdfReference rRef, bool bForce) = 0;
virtual void FreeObjectMemory(PoDoFo::PdfObjectImpl* pObj, bool bForce) = 0;
virtual PoDoFo::PdfEncryptImpl* GetEncrypt() const = 0;
virtual PoDoFo::EPdfWriteMode GetWriteMode() const = 0;
virtual void SetWriteMode(PoDoFo::EPdfWriteMode write_mode) = 0;
virtual PoDoFo::EPdfVersion GetPdfVersion() const = 0;
virtual void SetPdfVersion(PoDoFo::EPdfVersion pdf_version) = 0;
