/***************************************************************************
 *   Copyright (C) 2006 by Dominik Seichter                                *
 *   domseichter@web.de                                                    *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU Library General Public License as       *
 *   published by the Free Software Foundation; either version 2 of the    *
 *   License, or (at your option) any later version.                       *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU Library General Public     *
 *   License along with this program; if not, write to the                 *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 *   In addition, as a special exception, the copyright holders give       *
 *   permission to link the code of portions of this program with the      *
 *   OpenSSL library under certain conditions as described in each         *
 *   individual source file, and distribute linked combinations            *
 *   including the two.                                                    *
 *   You must obey the GNU General Public License in all respects          *
 *   for all of the code used other than OpenSSL.  If you modify           *
 *   file(s) with this exception, you may extend this exception to your    *
 *   version of the file(s), but you are not obligated to do so.  If you   *
 *   do not wish to do so, delete this exception statement from your       *
 *   version.  If you delete this exception statement from all source      *
 *   files in the program, then also delete it here.                       *
 ***************************************************************************/

/*
 * WARNING: This file was automatically generated by Beautiful Capi!
 * Do not edit this file! Please edit the source API description.
 *
 * Beautiful Capi project:
 * https://github.com/PetrPPetrov/beautiful-capi
 *
 * PoDoFo API description project:
 * https://github.com/GkmSoft/podofo-capi
 */


virtual ~PdfPage() {}
virtual PoDoFo::PdfRect GetPageSize() const = 0;
virtual bool SetPageWidth(int newWidth) = 0;
virtual bool SetPageHeight(int newHeight) = 0;
virtual void SetTrimBox(PoDoFo::PdfRect rSize) = 0;
virtual unsigned GetPageNumber() const = 0;
virtual PoDoFo::PdfRect CreateStandardPageSize(PoDoFo::EPdfPageSize ePageSize, bool bLandscape) = 0;
virtual PoDoFo::PdfObject* GetContents() const = 0;
virtual PoDoFo::PdfObject* GetContentsForAppending() const = 0;
virtual PoDoFo::PdfObject* GetResources() const = 0;
virtual PoDoFo::PdfRect GetMediaBox() const = 0;
virtual PoDoFo::PdfRect GetCropBox() const = 0;
virtual PoDoFo::PdfRect GetTrimBox() const = 0;
virtual PoDoFo::PdfRect GetBleedBox() const = 0;
virtual PoDoFo::PdfRect GetArtBox() const = 0;
virtual int GetNumAnnots() const = 0;
virtual PoDoFo::PdfAnnotation* CreateAnnotation(PoDoFo::EPdfAnnotation eType, PoDoFo::PdfRect rRect) = 0;
virtual PoDoFo::PdfAnnotation* GetAnnotation(int index) = 0;
virtual void DeleteAnnotation(int index) = 0;
virtual void DeleteAnnotation(PoDoFo::PdfReference ref) = 0;
virtual int GetNumFields() const = 0;
virtual PoDoFo::PdfField GetField(int index) const = 0;
virtual PoDoFo::PdfObject* GetFromResources(PoDoFo::PdfName rType, PoDoFo::PdfName rKey) = 0;
virtual PoDoFo::PdfObject* GetInheritedKey(PoDoFo::PdfName rName) const = 0;
virtual PoDoFo::PdfObject* GetOwnAnnotationsArray(bool bCreate, PoDoFo::PdfDocument* pDocument) = 0;
virtual int GetRotation() const = 0;
virtual void SetRotation(int rotation) = 0;
